version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    container_name: elasticsearch
    environment:
    - xpack.security.enabled=false
    - discovery.type=single-node
    - path.repo=/snapshots
    cap_add:
    - IPC_LOCK
    volumes:
    - type: volume
      source: /mnt/ceph/storage/data-in-progress/targer/index/srv/data/targer
      target: /srv/data/targer
    - type: volume
      source: /mnt/ceph/storage/data-in-progress/targer/snapshot
      target: /snapshots
    ports:
    - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.3
    container_name: kibana
    environment:
    - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
    - 5601:5601
    depends_on:
    - elasticsearch
