version: 2
updates:
  - package-ecosystem: pip
    directory: /backend/
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /backend/
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /batch_processing/
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /frontend/
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /frontend/
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
