version: "3"
services:
  frontend:
    build: ./frontend/
    ports:
      - 6001:6001
    networks:
      - arg
  backend:
    build: ./backend/
    ports:
      - 6000:6000
    networks:
      - arg
    volumes:
      - ./models/:/emnlp2017-bilstm-cnn-crf/models/

networks:
  arg:


