# Default values for targer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

frontend:
  port: 30294
  image: webis/targer-frontend:latest
  replicaCount: 3

backend:
  port: 30293
  image: webis/targer-backend:latest
  replicaCount: 3

# Paths of models and index snapshot on each host's file system.
modelsPath: /mnt/ceph/storage/data-in-progress/targer/models/
indexPath: /mnt/ceph/storage/data-in-progress/targer/index/

# Elasticsearch configuration
elasticsearch:
  esConfig:
    elasticsearch.yml: |
      path.repo: ["/targer-index"]
      repositories.url.allowed_urls: ["https://ltdata1.informatik.uni-hamburg.de/targer/*", "https://files.webis.de/data-in-production/targer/*"]
