apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Chart.Name }}-backend
  name: {{ .Chart.Name }}-backend
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-backend
  replicas: {{ .Values.backend.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-backend
    spec:
      containers:
      - name: {{ .Chart.Name }}-backend
        image: {{ .Values.backend.image }}
        resources:
          requests:
            memory: 15Gi
        volumeMounts:
        - mountPath: /emnlp2017-bilstm-cnn-crf/models/
          name: {{ .Chart.Name }}-backend-models
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: {{ .Chart.Name }}-backend-models
        hostPath:
          path: {{ .Values.backend.modelsPath }}
          type: Directory
