apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-backend
spec:
  type: NodePort
  selector:
    app: {{ .Chart.Name }}-backend
  ports:
  - nodePort: {{ .Values.backend.port }}
    port: 6000
    targetPort: {{ .Chart.Name }}-backend-port
