apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-frontend-config-map
data:
  config.ini: |
    [frontend]
    host = 0.0.0.0
    port = 6001
    api_endpoint = {{ .Values.backend.url }}
    es_host = {{ .Values.elasticsearch.host }}
    es_port = {{ .Values.elasticsearch.port }}
    es_index = {{ .Values.elasticsearch.index }}
    source_url = {{ .Values.info.sourceUrl }}
    api_url = {{ .Values.backend.url }}apidocs/
    paper_doi = {{ .Values.info.paperDoi }}
