apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-frontend-config-map
data:
  config.ini: |
    [DEV]
    publish_host = 0.0.0.0
    publish_port = 6001
    backend_host = {{ .Chart.Name }}-backend
    backend_port = 6000
    es_host = {{ .Chart.Name }}-es-master
    es_port = 9200
