apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: {{ .Chart.Name }}-frontend
  name: {{ .Chart.Name }}-frontend
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-frontend
  replicas: {{ .Values.frontend.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-frontend
    spec:
      containers:
      - name: {{ .Chart.Name }}-frontend
        image: {{ .Values.frontend.image }}
      restartPolicy: Always
