apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-frontend
spec:
  type: NodePort
  selector:
    app: {{ .Chart.Name }}-frontend
  ports:
  - nodePort: {{ .Values.frontend.port }}
    port: 6001
    targetPort: {{ .Chart.Name }}-frontend-port
