apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-frontend
  {{- with $.Values.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    service: {{ $.Release.Name }}-frontend
spec:
  selector:
    matchLabels:
      app: {{ $.Release.Name }}-frontend
  replicas: {{ $.Values.frontend.replicas }}
  template:
    metadata:
      annotations:
        checksum/frontend-config-map: {{ include (print $.Template.BasePath "/frontend-config-map.yml") . | sha256sum }}
        checksum/elasticsearch-login: {{ include (print $.Template.BasePath "/elasticsearch-login.yml") . | sha256sum }}
      labels:
        app: {{ $.Release.Name }}-frontend
    spec:
      containers:
      - name: {{ $.Release.Name }}-frontend
        image: {{ $.Values.frontend.image }}
        {{- if and $.Values.elasticsearch.username $.Values.elasticsearch.password }}
        env:
          - name: ES_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ $.Release.Name }}-elasticsearch-login
                key: username
          - name: ES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ $.Release.Name }}-elasticsearch-login
                key: password
        {{- end }}
        volumeMounts:
        - name: {{ $.Release.Name }}-frontend-config
          mountPath: /config.ini
          readOnly: true
          subPath: config.ini
        {{/*
        startupProbe:
          httpGet:
            port: {{ $.Values.frontend.servicePort }}
            path: /apidocs/
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6 # Wait 6*10 = 600 seconds to start webserver.
        */}}
        readinessProbe:
          httpGet:
            port: {{ $.Values.frontend.servicePort }}
            path: /apidocs/
          initialDelaySeconds: 60 # Wait 60 seconds to start webserver.
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
        livenessProbe:
          httpGet:
            port: {{ $.Values.frontend.servicePort }}
            path: /apidocs/
          initialDelaySeconds: 60 # Wait 60 seconds to start webserver.
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 12
      restartPolicy: Always
      volumes:
      - name: {{ $.Release.Name }}-frontend-config
        configMap:
          name: {{ $.Release.Name }}-frontend-config-map