apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}-models
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
  - ReadOnlyMany
  hostPath:
    path: {{ .Values.modelsPath }}
    type: Directory
