name: "Docker build"

on: push

jobs:
  build-frontend:
    name: "🚀 Build frontend image"
    runs-on: ubuntu-18.04
    steps:
    - name: "📥 Check-out"
      uses: actions/checkout@v4
    - name: "🚀 Build Docker image"
      uses: docker/build-push-action@v1
      with:
        path: frontend
        push: false
  build-backend:
    name: "🚀 Build backend image"
    runs-on: ubuntu-18.04
    steps:
    - name: "📥 Check-out"
      uses: actions/checkout@v4
    - name: "🚀 Build Docker image"
      uses: docker/build-push-action@v1
      with:
        path: backend
        push: false
